### ISSUE TITLE
[Bug] No colors / Colors disappear when switching colorschemes

### ISSUE THREAD

**Issue by oredaze** [LeonHeidelbach/trailblazer.nvim#42] opened 2023-04-08 12:22 UTC
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Void Linux

### Describe the bug

When using most colorschemes no colors are present. The ones that do have colors lose them upon switching the colorscheme (even to itself).
Tested with clean neovim config too. With or without custom trailblazer configuration makes no difference. You can change the colors and all, trailblazer works and configuring it works fine, but...

### Steps To Reproduce

1. Create a clean neovim config
2. Use vim-plug to install TrailBlazer.nvim
3. Install some colorschemes
4. Switch them with `:colorshceme foo`

### Expected Behavior

Colors should be present.

**Comment by LeonHeidelbach** [comment] 2023-04-08 13:08
@oredaze This is caused by some colorscheme scripts running `:hi clear` which wipes all highlight groups that have been set. This has been fixed in here 674bb6254a376a234d0d243366224122fc064eab, good catch :+1: .

**Closed by LeonHeidelbach** 2023-04-08 13:08 UTC
Labels: bug
